name: Main CI
on:
  push:
    branches:
      - main
jobs:
  bump-tag-version:
    name: Bump and Tag Version
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v2
      
      - name: Bump and Tag Version
        id: bump_tag
        uses: jefflinse/pr-semver-bump@v1.6.0
        with:
          mode: bump
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Generate Release Name
        id: release_name
        run: |
          formatted_date=$(date +'%b %d, %Y')
          echo "name=Release v${{ steps.bump_tag.outputs.version }} ($formatted_date)" >> $GITHUB_OUTPUT
      
      - name: Generate Release Notes
        id: release_notes
        uses: gableroux/generate-github-release-notes@v0.1.2
        with:
          repository: ${{ github.repository }}
          base_tag: ${{ steps.bump_tag.outputs.old-version }}
          head_tag: ${{ steps.bump_tag.outputs.version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          auto_detect_new_contributors: true

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.release_name.outputs.name }}
          body: ${{ steps.release_notes.outputs.notes }}
          tag_name: ${{ steps.bump_tag.outputs.version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
